### ISSUE TITLE
debug menu stuck in caps for chromebook

### ISSUE THREAD

**Issue by pizzatowerfan126** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#1]
I don't know how to stop it from doing this.

**Comment by burnedpopcorn** [comment]
Can you provide a screenshot and some context, because I've never seen a "debug menu" when using a chromebook (other than the console)

**Comment by pizzatowerfan126** [comment]
the console is the debug menu.

**Comment by burnedpopcorn** [comment]
You should be able to press the "toggle console" button again to turn it off, or just wait for the game to load, as the game frame usually is big enough to obscure it for me

**Comment by pizzatowerfan126** [comment]
ok thx

**Comment by BFDIFirey** [comment]
@burnedpopcorn how do you activate debug mode?

**Comment by BFDIFirey** [comment]
@pizzatowerfan126  how do you activate it
