### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by dontaskmeaxy** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#10]
Whenever I launch the web port there’s always no sound. Tested on both chromebook and windows pc, no audio at all. 

P.S: is it okay if i make multiple issues because there are?

**Comment by dontaskmeaxy** [comment]
I’m dumb and didn’t read ignore this

**Comment by burnedpopcorn** [comment]
Yeah, but read the Readme first. Because I've already posted known issues there including this one, so put an issue that I haven't found

**Comment by martenmario64** [comment]
can you close this?
