### ISSUE TITLE
Clothes don't work

### ISSUE THREAD

**Issue by dontaskmeaxy** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#12]
Playing as The Noise (peppino not tested) when you go to change clothes/palettes, the palette stays the same. The only change is the afterimages, as they change color depending on the palette.

**Comment by kobykk** [comment]
> Playing as The Noise (peppino not tested) when you go to change clothes/palettes, the palette stays the same. The only change is the afterimages, as they change color depending on the palette.

just deal with it or if your recording you can edit the clothes in

**Comment by burnedpopcorn** [comment]
Yeah, I have absolutely no idea how clothes work in the code, nor is it a high priority issue to fix, so I will not be working on this anytime soon

(Also just as a reminder, I don't have much time for this port or even my other projects at the moment, so expect fixes to rarely appear)

**Comment by kobykk** [comment]
> Yeah, I have absolutely no idea how clothes work in the code, nor is it a high priority issue to fix, so I will not be working on this anytime soon
> 
> (Also just as a reminder, I don't have much time for this port or even my other projects at the moment, so expect fixes to rarely appear)

i found a video that explains that on yt

**Comment by burnedpopcorn** [comment]
If you can, then share it. I guess it wouldn't hurt to watch

**Comment by kobykk** [comment]
> If you can, then share it. I guess it wouldn't hurt to watch

all i could find was custom clothes tutorials

**Comment by BFDIFirey** [comment]
it is because if it were white the sprites would be messed up

**Comment by Neybo** [comment]
the whole "clothes" system is based of retro palette swapper with modifications on it
sadly the palette code mostly depends on surfaces that might confuse the game in other situations

**Comment by nolan540** [comment]
> Yeah, I have absolutely no idea how clothes work in the code, nor is it a high priority issue to fix, so I will not be working on this anytime soon
> 
> (Also just as a reminder, I don't have much time for this port or even my other projects at the moment, so expect fixes to rarely appear)

I know you said you don't how it works but makes ask do you copy the games code or is it a hand written thing if you did copy the code surprised it don't work not complaining though

**Comment by burnedpopcorn** [comment]
Wdym copying code? As in how I load it into Gamemaker and compile it, or do you think I just copy and paste code into GameMaker as a way to fix issues? I don't understand the question

**Comment by nolan540** [comment]
now that I think about it I feel kinda stupid

**Comment by burnedpopcorn** [comment]
Well, what did you have in mind while typing that?

**Comment by nolan540** [comment]
i was thinking like if codes are somehow pasted into the game and clothes dont work that question popped into my head

**Comment by burnedpopcorn** [comment]
No, shit like Game Genie codes don't work or even exist. I modify the source code just enough to make it compatible with the Browser, and then I change my compile target from Windows to GX.GAMES (Technically Web Assembly). I don't use Javascript because its incompatible with almost all of the game code, and it's just generally terrible. Web Assembly is a lot better.

**Comment by burnedpopcorn** [comment]
Also, I especially don't understand you saying something about "Handwritten" codes. Everything is inherently Online. How the hell could something of this nature be handwritten
