### ISSUE TITLE
Useless Yet Humourous Crash Detected

### ISSUE THREAD

**Issue by AJNurtnick** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#13]
When I was doing some speedrunning and playtesting, something interesting occurred.

While Knight Peppino likes to crash the program when hitting a wall, something similar occurs when giving the final bit of money to the Noisette rabbit thing. I would presume the same thing happens with Mr. Mooney, but I have yet to find out.

It is a smaller non-essential problem, but I just thought I'd let ya' know.
![Screenshot 2024-05-31 11 20 15 AM](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/171276959/7389b0ee-72b3-4b89-a57f-1c8992cc1b73)

**Comment by burnedpopcorn** [comment]
Wdym, like nosiette crashes when paying for fake peppino?

**Comment by AJNurtnick** [comment]
Sorry for the late reply.

Noisette works fine, I got all the way to Pizzaface. The problem comes from giving the remaining money after the Pizzaface door on the final floor, where paying the Mr. Mooney stand-in crashes the game. Like Mr. Mooney, it only unlocks a pair of clothes (which don't even seem to be working at the moment), so it's not essential to beating the game.

**Comment by burnedpopcorn** [comment]
Thanks for the image of the error report, it helps a lot when trying to figure out the problem

**Comment by burnedpopcorn** [comment]
Although this helps, I still need to experience this crash for myself, as I'm not entirely sure on the context of this crash, so that might take some time

**Comment by dontaskmeaxy** [comment]
i was going to make an issue but just saw this, exact same thing happens

**Comment by burnedpopcorn** [comment]
Also, because you're speedrunning, I'm gonna mention that the Knight Peppino Crash has been Patched. Enjoy being able to actually play PizzaScape

**Comment by burnedpopcorn** [comment]
@AJNurtnick, this has been fixed now :)

Thanks for informing me about this
