### ISSUE TITLE
Just saying, the gameframe extension depends on windows-related stuff

### ISSUE THREAD

**Issue by Neybo** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#15]
gameframe is misplaced because a lack of borderless window in web export 
the only way you would fix it is remove the extension and remove the function that calls the extension functions

**Comment by burnedpopcorn** [comment]
Yeah, I could do that and reimpliment the old rendering code from older verisons like the April 2021 build, but honestly, I have no idea where I would start

**Comment by burnedpopcorn** [comment]
I mean, it could work, but gameframe seems to be a big dependency, so wouldn't the game crash without it? and even if it doesn't crash, wouldn't that screw up other visuals and other graphics related code?

**Comment by burnedpopcorn** [comment]
or are you talking about replacing the current obj_screensizer with the one from the April build (if it even has it)

**Comment by burnedpopcorn** [comment]
Thanks again, and ima close this issue eventually
