### ISSUE TITLE
the game recieves error

### ISSUE THREAD

**Issue by FINITE-IS-FAKE97** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#16]
when i load either version it says that it couldnt load a texture

**Comment by FINITE-IS-FAKE97** [comment]
nvm

**Comment by FINITE-IS-FAKE97** [comment]
i still crashed

**Comment by FINITE-IS-FAKE97** [comment]
it says "error in action number 1 of create event for object obj_textureloading:"

**Comment by FINITE-IS-FAKE97** [comment]
even after i cleared the site cache

**Comment by burnedpopcorn** [comment]
I have instructions on how to clear cache, but because I don't have access to my computer right now, you just have to wait until then

Honestly I should have posted instructions sooner

**Comment by FINITE-IS-FAKE97** [comment]
k also it talks about the loading screen texture not being able to load

**Comment by burnedpopcorn** [comment]
Yeah, again it's a outdated cache issue, please clear all site data and cached images

I'll post instructions eventually, so if you don't know how to, please be patient

**Comment by FINITE-IS-FAKE97** [comment]
ok

**Comment by burnedpopcorn** [comment]
Yeah, I'm currently finishing up another update rn, so you might wanna wait on clearing cache unless you really wanna play rn

**Comment by burnedpopcorn** [comment]
I've revamped the Level Select once again and I've replaced the FMOD logo with my profile and github

Honestly I think the Level Select Title Card came out really well

**Comment by burnedpopcorn** [comment]
It'll be up when I finish compiling it

**Comment by burnedpopcorn** [comment]
The instructions have been integrated into the README, so read that

Also, Revision 5 has been applied on the main site
