### ISSUE TITLE
modding :) (and scoudigo)

### ISSUE THREAD

**Issue by Goofybro7** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#17]
is there any way you can support the mods? And can you port pizza tower scoudigo (v1 and v2 pls) as a web port also?

PPPPPPLLLLSSSS LOL

**Comment by burnedpopcorn** [comment]
Mods are not being considered at the moment.

Also I have never heard of Pizza Tower Scoudigo, so I gotta try it out before I attempt a web port and even then I have to find the source code of it, which might be difficult

And then there could be other issues along the way, but if I find source code I could give porting a try (no promises tho)

**Comment by Goofybro7** [comment]
> Mods are not being considered at the moment.
> 
> Also I have never heard of Pizza Tower Scoudigo, so I gotta try it out before I attempt a web port and even then I have to find the source code of it, which might be difficult
> 
> And then there could be other issues along the way, but if I find source code I could give porting a try (no promises tho)

here is the source code i did not go in to the link so idk if its really it.. https://www.youtube.com/watch?v=eoHOUO1kM8I

**Comment by burnedpopcorn** [comment]
Thanks for the source code link, but unfortunately, I can't do it anymore. 

Its not that I don't want to, its just that I have no means of making (or even updating) ports anymore. I can't even update my Noise port anymore. Sorry for the bad news

But as soon as I can, I'll try and work on it, but I'm not sure how long I'll have to wait, but It might be a long time, so don't expect any updates any time soon :(

**Comment by burnedpopcorn** [comment]
@Goofybro7 I will try and work on porting Scoudigo v1.2 whenever I can (but considering my current situation, it will take a long time).

Supporting Mods on the other hand will probably not happen. I already got to fix the current issues, which are pretty big and will be very time consuming

**Comment by Goofybro7** [comment]
> @Goofybro7 I will try and work on porting Scoudigo v1.2 whenever I can (but considering my current situation, it will take a long time).
> 
> Supporting Mods on the other hand will probably not happen. I already got to fix the current issues, which are pretty big and will be very time consuming

Okay dokey 👌🏼

**Comment by burnedpopcorn** [comment]
> > Okay dokey 👌🏼 I think pizza tower cheesed up would be easier for you to port

@Goofybro7 I tried Cheesed Up, but its a lot different from stock PT, and there are way too many Windows Only Extensions in cheesed up and way too many compiler errors, so I kinda give up on that port

Hopefully Scoutdigo is different tho

**Comment by burnedpopcorn** [comment]
@Goofybro7 so things took a 180

CheesedUp somehow ended up being the one I managed to port first, but it needs a lot of polish and work

Scoudigo also somehow ended up being the most disorganized shit I have seen, plus I'm pretty sure it's supposed to be a xdelta file or something that has to be injected into the stock game, so if that's the case, Scoudigo port is not happening at all

**Comment by burnedpopcorn** [comment]
@Goofybro7 if you want to play Cheesed Up, go here: https://theprojects.x10.mx/runner.html

**Comment by burnedpopcorn** [comment]
@Goofybro7 
So...
I did get Scoutdigo to work
right now its a heavy WIP, but be ready for a Web Port to drop soon
(if you still care)

**Comment by Goofybro7** [comment]
> @Goofybro7 So... I did get Scoutdigo to work right now its a heavy WIP, but be ready for a Web Port to drop soon (if you still care)

lets goooooo so cool dude

**Comment by burnedpopcorn** [comment]
I forgot to mention I released it
Find it in my Pinned Repos
