### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alexdadumbum** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#18]
yo so when i opened the app it  said error for loading in and it kicked me out but yesterday it was doing fine pls fix bc i was at 99%

**Comment by alexdadumbum** [comment]
![Screenshot 2024-06-13 7 58 03 PM](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/159989370/6996a4c9-1b4a-4dd5-b1f6-7c476401216b)

**Comment by AJNurtnick** [comment]
I believe that was because of the update to the port. If you follow the instructions on the README and delete the site's cache, it should start functioning. That's how it worked for me.

**Comment by burnedpopcorn** [comment]
Yeah, this is the log I ALWAYS get when I update the site and hadn't cleared my cache, so please clear it
