### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by BFDIFirey** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#2]
How do you activate debug mode

**Comment by burnedpopcorn** [comment]
For the Debug Console, Press F5 while ingame, although I don't know any commands, so I can't check to see if it works

**Comment by BFDIFirey** [comment]
@burnedpopcorn is there another way on chromebook (I'm tired of these dumb schools not giving us windows computers)

**Comment by burnedpopcorn** [comment]
I think what you can do is hold the Search key (the one that would be in place of Caps Lock) and then press 5, which apparently is the way to press f5 on chromebook (I'll try and confirm this myself)

**Comment by burnedpopcorn** [comment]
Unfortunately the Search+5 key combo didn't work, but I did manage to modify the game to open the menu with F5 OR the Tab key, but commands don't work for some reason (I have no idea how to fix that tbh, so don't expect me to fix this anytime soon)

**Comment by BFDIFirey** [comment]
oh ok

**Comment by BFDIFirey** [comment]
/
