### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by naufal4447777** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#20]
When I starting a game it keep crashing
And, that's it

**Comment by burnedpopcorn** [comment]
Look at the README's instructions for Clearing Cache. Outdated cache from older builds are still referenced and conflict with the new build, causing a crash, so delete the cache and the site should work.
> This needs to be done every time an update is rolled out unfortunately

Please tell me if this solved your issue or not as soon as you can
