### ISSUE TITLE
It's Joever

### ISSUE THREAD

**Issue by BFDIFirey** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#21]
my school took my Chromebook during the school hours I will miss this fun experience I haven't played any of it

**Comment by burnedpopcorn** [comment]
that sucks, they gonna give it back?

**Comment by BFDIFirey** [comment]
next school year but my summer school has windows computers

**Comment by burnedpopcorn** [comment]
well, I bet the windows computers are better tho :)

(And faster)
