### ISSUE TITLE
I need this

### ISSUE THREAD

**Issue by AppleDoise** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#24]
I need this transplant
![6694b8e1be8df](https://github.com/user-attachments/assets/24409bd2-bc45-498c-bf2a-d0f0de8f9305)

**Comment by ShyGuyComputer** [comment]
they won't do xdelta mods

**Comment by burnedpopcorn** [comment]
@AppleDoise @ShyGuyComputer 
Please continue this conversation on the discord server

[![Discord Invite Link](https://theprojects.x10.mx/discord.jpg)](https://discord.gg/BJSkBEPU)

I just dont want issues to be flooded with general chat instead of actual issues, so please go there
