### ISSUE TITLE
is the pizza gaultlet in the web port because I did everything it told me to do and I still cant find it

### ISSUE THREAD

**Issue by chubbybelly24** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#25]

**Comment by burnedpopcorn** [comment]
Don't know what pizza gauntlet is
But I doubt it is in this one

**Comment by chubbybelly24** [comment]
I will show you on discord

**Comment by chubbybelly24** [comment]
I'm in the share vids

**Comment by chubbybelly24** [comment]
its where you go through every level kind of like secrets of the world

**Comment by burnedpopcorn** [comment]
OHHH
Yeah, that should be In the game, but you have to unlock it the normal way

**Comment by Chubbybelly23** [comment]
I did tell me the normal way and I will see if I got those done or not

**Comment by burnedpopcorn** [comment]
I don't know the normal way
Just search it up on Google

**Comment by pepperman2023** [comment]
pizza gauntlet isnt in the web port its part of the lap hell mod

**Comment by chubbybelly24** [comment]
I have the pt cheesed up web port but its not the latest source code but Its from your web port

**Comment by chubbybelly24** [comment]
https://www.autistici.org/burnedprojects/cheesedupnew/runner.html or it might be

**Comment by chubbybelly24** [comment]
nevermind its[ ](https://www.autistici.org/burnedprojects/cheesedup/runner.html)

**Comment by chubbybelly24** [comment]
https://www.autistici.org/burnedprojects/cheesedup/runner.html
