### ISSUE TITLE
 Just crash

### ISSUE THREAD

**Issue by justaguy0671** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#26]
Idk if it just because my device im on is just less powerful but when I launch the game it just crashes

**Comment by burnedpopcorn** [comment]
Does it say ```Exception Thrown, See JavaScript Console```, or does it just not load

Also consider clearing your site cache, as that sometimes can cause crashes

**Comment by justaguy0671** [comment]
No like when I skip the cutscene it crashes

**Comment by burnedpopcorn** [comment]
hmm
Well no one else has that issue
Try clearing site cache, and Toggle Console to see what message you get

**Comment by justaguy0671** [comment]
Ok

**Comment by justaguy0671** [comment]
This is solved right?

**Comment by justaguy0671** [comment]
When I go in don’t make a sound it crashes

**Comment by burnedpopcorn** [comment]
Idk, it works fine for me, and not one else has that issue

**Comment by burnedpopcorn** [comment]
gonna close this issue since literally no one else has that issue, you're not specifiying which build, and you're not responding anyways
