### ISSUE TITLE
Exception Thrown, see javascript console

### ISSUE THREAD

**Issue by RetroTheProtogen111** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#3]
It starts to load, showind "Downloading Data" but then says, "Exception Thrown, see javascript console"
I would give what it says in the javascript console, but my school disabled inspect element
![Screenshot 2024-05-13 8 38 16 AM](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/169670862/f23314bb-f44a-450f-a596-3e53562d189b)

**Comment by burnedpopcorn** [comment]
I can't seem to replicate this issue myself, but on school chromebooks I would have a problem similar to this one, and I would fix it by logging out and logging in again.

**Comment by dontaskmeaxy** [comment]
same here, literally can't even play as it either loads and gives me a black screen or just says that
