### ISSUE TITLE
some of the commands in the console don't work 

### ISSUE THREAD

**Issue by Bigmoneyman** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#30]

**Comment by Bigmoneyman** [comment]
player set state doesn't work

**Comment by burnedpopcorn** [comment]
Yeah, for some reason WASM Export makes all inputs to be Upper Case
I'm guessing its a keyboard driver issue on GameMaker's part, but yeah
known issue that probably won't be solved

**Comment by Bigmoneyman** [comment]
ok, thanks for telling me!
