### ISSUE TITLE
can you add pizza tower round 2

### ISSUE THREAD

**Issue by thenoise23** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#31]

**Comment by thenoise23** [comment]
well if you can add it I will be happy but if u don't then I will still be happy because your the best maker ever

**Comment by burnedpopcorn** [comment]
I did decompile it so I could try to, but my discord server decided that Full Course would be a better one to try and port

also thanks

**Comment by thenoise23** [comment]
np bro
