### ISSUE TITLE
plz add stuff from lap hell and ur pizza tower cheesed up web port(and plz fix sound

### ISSUE THREAD

**Issue by Butterbean0331** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#32]

**Comment by burnedpopcorn** [comment]
1. no for lap hell
2. what about my Cheesed Up Web Port?
3. Yeah, i'm fixing every problem with Sound for this Web Port

also if you want to respond, please talk to me in my Discord

**Comment by Pro2219** [comment]
So, no lap hell?
