### ISSUE TITLE
can you try to add pizza tower co-op not swap mode 

### ISSUE THREAD

**Issue by thenoise23** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#33]

**Comment by thenoise23** [comment]
also co-op is that the 2nd player can move while the 1st player is moving and can still attack the enemy's  and attack player 1

**Comment by thenoise23** [comment]
just letting ya know

**Comment by burnedpopcorn** [comment]
This port won't be getting mods anytime soon
that's what my other ports are for
