### ISSUE TITLE
burnedpopcorn can you add pizza tower co-op?

### ISSUE THREAD

**Issue by thenoise23** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#35]
its like when player 2 can move and stuff and kill enemies  with player 1 aka player 2 the noise it would be nice if you could do that

**Comment by thenoise23** [comment]
also what I'm meaning by co-op

**Comment by thenoise23** [comment]
Is that adding it in the pizza tower web port

**Comment by burnedpopcorn** [comment]
yeah, no
also this is for issues, if you want to make a suggestion, go to the discord and a make suggestion
