### ISSUE TITLE
why don't you want to add lap 3 in the pizza tower noise update?

### ISSUE THREAD

**Issue by thenoise23** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#37]
is something wrong with it?

**Comment by burnedpopcorn** [comment]
No, just I'm not willing to add it
If you want to play Lap 3, play my Cheesed Up Port

Also, stop making issues just to contact me
If you want to contact me, join my discord

**Comment by thenoise23** [comment]
uhhhh okay.

**Comment by thenoise23** [comment]
but ur cheesed up is gone right?

**Comment by burnedpopcorn** [comment]
No, it's still available on my Discord
The creator of the mod got butthurt and falsely took it down

**Comment by thenoise23** [comment]
oh okay

**Comment by shanekanichols1990-debug** [comment]
can you make lap 3 deluxe web port
