### ISSUE TITLE
my noise update save file got deleted and it reset EVERYTHING including clothes and i dont even have a peppino file

### ISSUE THREAD

**Issue by kobykk** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#4]
my mum went on my computer and i think that was why my save files got deleted

**Comment by burnedpopcorn** [comment]
If that's what you think happened, why did you open this issue?

**Comment by burnedpopcorn** [comment]
Also, I probably can't help you recover it even if I wanted to, as there's no way I can think of to export (let alone import) a save, maybe through inspect element, but it can be disabled for people using school chromebooks, which if you have is probably why you have this issue, as logging out can delete saves

**Comment by kobykk** [comment]
> Also, I probably can't help you recover it even if I wanted to, as there's no way I can think of to export (let alone import) a save, maybe through inspect element, but it can be disabled for people using school chromebooks, which if you have is probably why you have this issue, as logging out can delete saves

its completely fine as i just speedrun all the floors and stop when i get to the slum but im doing a 5 part series where each floor is 1 part and i finished floor 1 so floor 2 is next

**Comment by kobykk** [comment]
> Also, I probably can't help you recover it even if I wanted to, as there's no way I can think of to export (let alone import) a save, maybe through inspect element, but it can be disabled for people using school chromebooks, which if you have is probably why you have this issue, as logging out can delete saves

im not using a chromebook or anything else other than a pc

**Comment by burnedpopcorn** [comment]
> > Also, I probably can't help you recover it even if I wanted to, as there's no way I can think of to export (let alone import) a save, maybe through inspect element, but it can be disabled for people using school chromebooks, which if you have is probably why you have this issue, as logging out can delete saves
> 
> its completely fine as i just speedrun all the floors and stop when i get to the slum but im doing a 5 part series where each floor is 1 part and i finished floor 1 so floor 2 is next

Then again, why did you open this issue?
