### ISSUE TITLE
uhmmm,secrets of the world is broken

### ISSUE THREAD

**Issue by ilikefnfmobile** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#40]
did you copy the offical switch port for this? because it's the exact same type of error.

**Comment by burnedpopcorn** [comment]
Yeah, d's script was the only way to add sound, but this is a known issue and will be fixed as soon as I can

**Comment by burnedpopcorn** [comment]
fixed
wasn't a problem with d's script
just that i compiled it with YYC
