### ISSUE TITLE
Dang crashes!

### ISSUE THREAD

**Issue by Chriclercrap** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#41]
Can't even get my free P rank in the doise boss fight because it crashes upon loading >:(

**Comment by burnedpopcorn** [comment]
I will try and replicate this myself, although no one else seems to have this issue

**Comment by burnedpopcorn** [comment]
Yeah, I didnt experience this crash when playing, so yeah...idk what could be your problem

**Comment by martenmario64** [comment]
ill see too

**Comment by Chriclercrap** [comment]
the screen turns white upon entering a boss sometimes

**Comment by Chriclercrap** [comment]
and normal levels to

**Comment by martenmario64** [comment]
odd, i did not get it

**Comment by martenmario64** [comment]
are you using r8 or r6?

**Comment by Chriclercrap** [comment]
R8

**Comment by martenmario64** [comment]
R8 does not crash for me :(

**Comment by martenmario64** [comment]
on the doise fight nope :(

**Comment by Chriclercrap** [comment]
I think it only happens if your lagging really badly

**Comment by Chriclercrap** [comment]
It stopped for now
