### ISSUE TITLE
editor prob

### ISSUE THREAD

**Issue by sheepyboiyt** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#46]
Honestly ive only been playing the webport for a few days and i tried going into the editor but it never works.
🥺 plz fix or tell me if im doing something wrong.

**Comment by burnedpopcorn** [comment]
Editor?
As in, some kind of Level Editor?
Because there is no such thing in this port

**Comment by sheepyboiyt** [comment]
what is this command for then because it always crashes when i use it

![Screenshot 2024-10-08 193229](https://github.com/user-attachments/assets/c12fa963-55b3-4a85-8a23-3e34f72ab97c)

**Comment by burnedpopcorn** [comment]
straight from the PT Wiki
```
editor - “Brings” the player to the level editor. When using this command, it crashes the game, making the command useless.
```

**Comment by sheepyboiyt** [comment]
Ahhh thx for the help. 😏 ngl an editor does sound pretty good but it might take lots of work. also i was going to tell u to add an editor in discord but we was already in github. MEH

**Comment by sheepyboiyt** [comment]
closed my bad

**Comment by burnedpopcorn** [comment]
i actually love level editors, but that's a lot of work
plus there's limitations with the way its compiled
so yeah, probably not gonna happen

im pretty sure cyop is open source tho...

**Comment by sheepyboiyt** [comment]
ok whats cyop

**Comment by sheepyboiyt** [comment]
nvm i searched it up

**Comment by SONIC123CDMANIA** [comment]
> im pretty sure cyop is open source tho...

If (and I mean IF) you do that, it'll have to be AFOM or CATWEBS (which from what I've heard at the discord is going to be CARTWEBS) unless the port is of a older version of Pizza Tower...which I'm fine with.
