### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by kobykk** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#6]
add infinites laps or whatever mod you want or this mod https://gamebanana.com/mods/513191

**Comment by burnedpopcorn** [comment]
I don't think I'll add mods anytime soon, especially if there's no source code available for it

**Comment by burnedpopcorn** [comment]
Although I am interested in porting Pizza Tower Cheesed Up, Although from a December  2023 build, as that's the only one I could find with source code

**Comment by kobykk** [comment]
> I don't think I'll add mods anytime soon, especially if there's no source code available for it

try actually downloading the mods and taking their source code

**Comment by kobykk** [comment]
> Although I am interested in porting Pizza Tower Cheesed Up, Although from a December 2023 build, as that's the only one I could find with source code

you can do it right now if you want also ill try to stay updated if you actually do that

**Comment by burnedpopcorn** [comment]
If I do port it to the browser I'll make another repo for it, and probably host it as well, but it will take time tho, I got some stuff to do first

**Comment by kobykk** [comment]
> If I do port it to the browser I'll make another repo for it, and probably host it as well, but it will take time tho, I got some stuff to do first

k

**Comment by BFDIFirey** [comment]
@kobykk i found your yt i subscribed!

**Comment by kobykk** [comment]
> @kobykk i found your yt i subscribed!

k

**Comment by burnedpopcorn** [comment]
@BFDIFirey @kobykk I finally made the Cheesed Up port

It needs some heavy work to fix major issues, but it works for the most part

But I can't host it because of my server's limitations, and I can't upgrade cuz no money, so yeah, I'll try and fix the game as well as finding a way to host it

Check out the port and it's progress [here](https://github.com/burnedpopcorn/CheesedUP-Web-Build)

**Comment by burnedpopcorn** [comment]
@BFDIFirey @kobykk You can now play Cheesed Up here: https://theprojects.x10.mx/runner.html
