### ISSUE TITLE
question

### ISSUE THREAD

**Issue by pizzatowerfan126** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#7]
does anybody know how to port a fan game to web?

**Comment by burnedpopcorn** [comment]
Which one?

**Comment by pizzatowerfan126** [comment]
dr robotniks ring racers

**Comment by burnedpopcorn** [comment]
Huh, never heard of it. It depends if the source code is available, and what programming language it was made in

**Comment by pizzatowerfan126** [comment]
it is

**Comment by pizzatowerfan126** [comment]
I can put the link

**Comment by pizzatowerfan126** [comment]
https://github.com/KartKrewDev/RingRacers/releases/tag/v2.2

**Comment by burnedpopcorn** [comment]
Yeah, it's made in C++, so I think you can use Emscripten to compile it for the web

**Comment by pizzatowerfan126** [comment]
i'd like to do that but idk how to compile and i need some one to teach me how.

**Comment by burnedpopcorn** [comment]
I'm not sure either, all I know is that it the compiler for my pizza tower port (because gamemaker uses it when compiling for gx.games)

**Comment by burnedpopcorn** [comment]
Base Emscripten is something I'm not very familiar with either, all I know is that it works

**Comment by pizzatowerfan126** [comment]
ok

**Comment by pizzatowerfan126** [comment]
im trying the codespace to see if that will work

**Comment by pizzatowerfan126** [comment]
it didn't work

**Comment by burnedpopcorn** [comment]
Well, what did you do? (Also I should have mentioned that depending on many factors based on how it was made, it might not work without some modification to the code)

**Comment by pizzatowerfan126** [comment]
when I was trying to debug some code when used run 1 code ran but nothing else did

**Comment by burnedpopcorn** [comment]
Well, as I said I don't know much about how to use base Emscripten, but I hope you can figure it out like I did for gamemaker

**Comment by pizzatowerfan126** [comment]
k
