### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by deezboe** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#8]
Hi, thank you SO MUCH for this info, I've been wanting to make a port of pizza tower online for my actually good unblocked games website but couldn't because html was blocked by a subscription but now that I know about this it helped me make my own Pizza Tower Online web port and thanks to this I've been learning a lot about optimization so thank you, the size of PTO went down by half its size and i didn't even remove any big content its crazy! also the x10hosting wasn't up at least at the time I'm writing this so I used Amazon S3 its a pretty good alternative to it.

**Comment by burnedpopcorn** [comment]
You're welcome. Honestly, I only provided the information for other people smarter than me to contribute to my project, but it is still nice to hear that someone found it useful. But I'm curious, is Amazon S3 free? because I didn't know that. Also could you provide the link to your own PTO port, because i'm curious if you made a similar port of this: [https://gx.games/games/ei0tns/pizza-tower-online-web-port/](https://gx.games/games/ei0tns/pizza-tower-online-web-port/)

**Comment by burnedpopcorn** [comment]
I found your website, its pretty cool, and I do like PTO, especially since you can move objects in-game in that version, really cool stuff

**Comment by deezboe** [comment]
> You're welcome. Honestly, I only provided the information for other people smarter than me to contribute to my project, but it is still nice to hear that someone found it useful. But I'm curious, is Amazon S3 free? because I didn't know that. Also could you provide the link to your own PTO port, because i'm curious if you made a similar port of this: https://gx.games/games/ei0tns/pizza-tower-online-web-port/

Amazon S3 is free but it has a lot of verification stuff that took me a while to get through and my port is similar to the gx.games ports but mine can actually run on chromebooks without crashing, and I also made the grinch level not broken.

Also about contributing to your project I think this might fix your game frame problem.

![Screenshot 2024-05-17 082645](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/154568361/7030cfc2-0919-45ed-ade7-1a0bd0a533f2)

![Screenshot 2024-05-17 082923](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/154568361/29ac4b68-82d0-4941-bf29-ee11bcd27d3f)

**Comment by BFDIFirey** [comment]
@deezboe can you bring back Godot tower in a separate project?

**Comment by deezboe** [comment]
> @deezboe can you bring back Godot tower in a separate project?

wdym do u want me to add back the html of godot tower?

**Comment by BFDIFirey** [comment]
@deezboe no like make it be its own thing like how pizza tower noise update got ported (what I mean is let it be available on your profile ) (what I also mean is just port it html5 and make it be available on your profile my school blocked Google sites)

**Comment by burnedpopcorn** [comment]
I don't think you can port it to html5, I tried that in my port and it did not work at all, and the gx.games export worked almost perfectly, so i won't recommend exporting to html5, as you would have to change lots of things to make it work. But yeah, I would agree on sharing the files tho

**Comment by BFDIFirey** [comment]
@burnedpopcorn uh can I get a April 2021 build instead of demo 2 of sugary spire?

**Comment by burnedpopcorn** [comment]
April 2021 build of what? Normal pizza tower?

**Comment by BFDIFirey** [comment]
yes normal pizza tower

**Comment by burnedpopcorn** [comment]
Yeah, I'll see

**Comment by burnedpopcorn** [comment]
i cant find the source of the April 2021 build anywhere, i wont be able to do it unless we can find it

**Comment by BFDIFirey** [comment]
I know I forgot to link it https://github.com/Angelos2008/PizzaTowerApril2021

**Comment by BFDIFirey** [comment]
why do they do this

**Comment by burnedpopcorn** [comment]
Idk, some people either got it from someone else and don't know themselves or they're too lazy to specify. It makes things harder because if I get a runtime that's too new, it can break things while compiling, and ones too old just flat out don't compile it

**Comment by burnedpopcorn** [comment]
They really need to specify because of this. Honestly not specifying makes the source code worthless, but at least we get it at all ig.

**Comment by BFDIFirey** [comment]
i know right?

**Comment by burnedpopcorn** [comment]
Since this is a build from the original creator, and he used the 2022 LTS for his very recent update, I'm gonna bet he used the LTS version for the April build as well

**Comment by burnedpopcorn** [comment]
Hopefully it works, and if it don't, idk what I'll do

**Comment by BFDIFirey** [comment]
ok I already ask the creator for the runtime

**Comment by burnedpopcorn** [comment]
Thanks, just tell me what he says

(Also I'm still gonna try LTS anyways just in case)

**Comment by BFDIFirey** [comment]
he might be inactive idk

**Comment by BFDIFirey** [comment]
"
use game maker studio 2023.4-6" what the creator said but I have no experience with it

**Comment by burnedpopcorn** [comment]
Yeah, I'll try LTS and that too, although I thought he said he didn't exactly know what verison or even the verison year?

Oh well, thanks for contacting him tho, that will help alot

**Comment by burnedpopcorn** [comment]
I compiled it using a runtime newer than the one he specified, and it crashed, but the main menu music actually played, which is better than i expected, especially because gamemaker moved shit around

**Comment by burnedpopcorn** [comment]
Well, now i have ideas of how i can impliment sound back into my port

**Comment by BFDIFirey** [comment]
wait test and see if the runtine he chosed worked

**Comment by burnedpopcorn** [comment]
Yeah, doing that rn

**Comment by burnedpopcorn** [comment]
The only one I could find is 2023.4.0.113, which I think is the one (as he said 2023.4-5, should be good enough)

**Comment by BFDIFirey** [comment]
oh well there still could somehow be a chance

**Comment by burnedpopcorn** [comment]
Yeah, let's hope it just works like my noise update port

**Comment by burnedpopcorn** [comment]
It fucking works, music and all, although the walkable main menu is pitch black, not sure if that's how the build is suppose to be

**Comment by BFDIFirey** [comment]
WOOHOO

**Comment by burnedpopcorn** [comment]
![Screenshot (14)](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/164114576/dd2daa92-9268-4c76-bc5c-d3ec84d59fb5)

**Comment by BFDIFirey** [comment]
can you release it!?

**Comment by burnedpopcorn** [comment]
![Screenshot (15)](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/164114576/45ba77a9-5fe3-4f54-b91b-ffe4ca035be8)

**Comment by burnedpopcorn** [comment]
yeah i can, but you'll be the one to host it, cuz my x10hosting account is already used up for my port

**Comment by burnedpopcorn** [comment]
![Screenshot (16)](https://github.com/burnedpopcorn/Pizza-Tower-1.1.0-Web-Port/assets/164114576/db0c948d-d468-4c87-9b4d-32adb8f0a119)

**Comment by BFDIFirey** [comment]
um it says free hosting is down

**Comment by burnedpopcorn** [comment]
alright, ima make a repo rn, it'll take a minute tho

**Comment by burnedpopcorn** [comment]
hold up, what?

**Comment by BFDIFirey** [comment]
bro Im not tripping

**Comment by burnedpopcorn** [comment]
oh yeah, @deezboe mentioned that as well. he said that he used Amazon S3, you should talk with him

**Comment by burnedpopcorn** [comment]
cuz i don't know much about Amazon web hosting and their plans

**Comment by BFDIFirey** [comment]
well is there anymore options?

**Comment by BFDIFirey** [comment]
wait how do I make the game work

**Comment by BFDIFirey** [comment]
and I how do I make it appear

**Comment by burnedpopcorn** [comment]
Alright, i made the repo, i'll talk to you there, and i'm gonna close this issue now. Repo is [here](https://github.com/burnedpopcorn/PizzaTower-April2021-WebPort/tree/main)

**Comment by burnedpopcorn** [comment]
also @deezboe, i think you still have to pay for what you use, so if you don't have money, stop using it. If not, cool

**Comment by BFDIFirey** [comment]
@burnedpopcorn  I GOT DEV MENU ON  CHROMEBOOK

**Comment by burnedpopcorn** [comment]
How'd you do it?

**Comment by BFDIFirey** [comment]
so you press the search key then press then press the button after Fullscreen but it is stuck in caps

**Comment by deezboe** [comment]
> so you press the search key then press then press the button after Fullscreen but it is stuck in caps

oh yeah it does kinda work in chromebook i think the caps issue has to do with the web port export messing with the code probably an easy fix is to make the cmd system not caps sensitive

**Comment by burnedpopcorn** [comment]
I'm gonna try and see if the windows export works, or if the code itself is fucked

Might not be able to since I'm not paying for Gamemaker

**Comment by burnedpopcorn** [comment]
Yeah, the windows export does have a functioning command prompt. Something about the gx.games export screws something up

**Comment by burnedpopcorn** [comment]
Also, I have managed to patch in a way to open the command prompt with F5 or the Tab key to make it easier for chromebooks, but I haven't released it because commands don't work

**Comment by BFDIFirey** [comment]
ok cool!
