### ISSUE TITLE
fix the crash when slam into wall glitch

### ISSUE THREAD

**Issue by FINITE-IS-FAKE97** [burnedpopcorn/Pizza-Tower-1.1.0-Web-Port#9]

**Comment by burnedpopcorn** [comment]
This is already a known issue listed in the readme

**Comment by kobykk** [comment]
then if your in swap mode swap to the noise before using the knight transformation, it dosent crash with the noise but it does with peppino if your in a noise save then your compelety fine as long as you arent playing in your swap mode save and with the peppino save yea you will just have to be VERY carefull of walls

**Comment by burnedpopcorn** [comment]
This was also known, and because of this ima close this issue

**Comment by burnedpopcorn** [comment]
This Crash has been Fixed

**Comment by FINITE-IS-FAKE97** [comment]
thanks
